language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-directenergie.git"
  - secure: Ia7N5MePDpzWZ1KlPAREr1W6ezWJOfmTmC24Re+92sHjY81RRf1UGmvBiRi0Z/K60zQV81GLcw7mCSSNLranHeyYBDX07Vowsa2/z2n4Ph2OL64wpK/tXq0FBzBakkansjfTPMB6a1XU8Aq4skkGGTQNTjMqQj0M/T5QxcRjneGn5RbUz61CzF/rKNwjH3ycwxGkDb35EwLJ5xAUOcMsUK4oPJST5ouVBYhDzVPFTpwk/5mVZkAjJF19I+VLSZJUWcznMhhn88eqq/F7XKAL8ZcwK8WmEA8xtdhGd7O0lZAptrQTxf+4fphq3uRm6uYWbopTUqPK8unGR2CsV4hSJR9MHmaa6T325nWzxVMznHBYq2XKkB6o3cDxMSjyL1A/bk6pizPmQsu6lNYJML2VbsyqtCRQY9xS2DCANpcXm/SbWciYj+ouKuhpk27B714EcXkgGF8Y4tDKRXAdJA7Cu8JJ9vLfp6lm2Y123EtbsQvd6K/evgowCm1bSzLQ4rkShAEdFapLW587oGGcaZ8WD1ygPQ/kK6tC1bZ/vGMRHd9+QJ1LKPfDg2vmjL/v56jssABRfidoI3WB/cFqLhc3Y3K9WuQLgSNys5wKWb4NoPFzWkhCKd2AUl0EKjufVd3wJWd6iG1yfyKKPACPOyHGvPBTUEIVbRHiZS8bX25v8QY=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn publish:cozy
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_c4669962f2f7_key -iv $encrypted_c4669962f2f7_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
