language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-directenergie.git"
  - secure: Z28GOvFbP0p75WJ+aTdUsw1hf1ZGnwns8nRL1X3lR1n4O09fBz707vUJVVVqr/jlh0TBFzXh1yvYbJcfqt1oibq0yw8+7hBYJUYEdz0BS6Kq8ahlNTiGXnIBbig2ARYkKK4JqQmtu8c064R5XYPUu2SgJxCe3DIPDtcXU1TQ/48KpEPqf1RakOlrjACqNi2JXpaJ+GlLuOPPCm5GYBEDA4FUVIkCHXZ05Niv7joXQ6NdhzWFnZVj8O2fd0Eipha2dM5NdJMbq/gmML1vHC+ofaImeMoHtmUsX0PnR8uhjdka5K/boSFJdnkTb3iW9qJUGGyTNRqak8KvkVaWJY+wv6vR2JUwuwKicUT8tBRE5drtrtacVFb5DD9CzBX1BUylfWhvFpG8i0YlA7nbh74PI67VypY5S9An5I7is+VrUJ35v4HY8h3I30DJfLgB3YRRCqhaxanmxO3/MBSJ+1F9U8RmJeC3MNSgeMboiRPSmeEgffgM0PF9uJg4J9FCwZME4X+eIhF2UxOxzUAgSmSRIpxZlz5zkMEMusYnQpHMTwUP0mmmVX6RzaJRT9IWPbHKA2q7k1kGSllWNE9N8UEe+il4olalrCm4P50+Rd3cZNR7HkpNlYGMK3NXUi5ROQJO12rQFvlVv8lmwbeYvajW1beGz9xmahH2MWIoSlNlHCE=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn publish:cozy
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_c4669962f2f7_key -iv $encrypted_c4669962f2f7_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
