language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-directenergie.git"
  - secure: KOGl8BaodF4S/mqWPBZcPdpPCE2y6tFtKRdVj4wVtZ66G9M7fDax5e/aCLYghZRttIu8l+dfMi09Yt4H34dBJhAmXLpByKE4PdVDgf8s0/H2AvORm9yse7z99aCBVi6WZr3WV2XNT5ciBV4fvheN2Gaqs46hK4i/C4NelopmEybNOIpie/NM22vbOixiazDmx3sAIyUfPOmsr+M9M+wVgx34rigz15Q+RNkGaROGij+CIQBvjA0ukb7KFu4wxXcGjW50DJIh9BxrRE4L588+zp3g0S66G7PKu44gr5vZSk0eRkYAM8r6FNoC/h5eaDevIhs2+q00U8X6BjojsEvy3KydQftaK/O0ZJHY6s+S2XXEziaYaXg8gcl9Ek867fxebhsYH5rcOIggZnLlMnoRRpJycYccLROWTXdYTQSrycknGncFeRfvx6P+oAYTTnm8othxgMCvGBqossl1DsVbK1+iGBe1kW8tqL84X2+ctNP3lC7tPSyILdvwGT2w4T24qnHY3Iu0vA81an51OsSZP8sPK440bi9nQGZ+lBMikRezt/IB01G1nrcxcq+KfnMWP6fAiP8n41pZXNHU1oBCPsYTpxr6V5Nnp2SNq9ZPB+gXJ0w8bQufB7XpvWAroDpw+fmNz+Aex28AgSSoEYWsct2vGSfNgeID4Pfv7G4P9uo=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn publish:cozy
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_c4669962f2f7_key -iv $encrypted_c4669962f2f7_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
